name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME}}/taskcraft-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_DNS}}
          username: ${{ secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            docker pull ${{secrets.DOCKER_USERNAME}}/taskcraft-backend:latest

            docker run --rm \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            ${{ secrets.DOCKER_USERNAME }}/taskcraft-backend:latest \
            npx prisma migrate deploy

            docker stop backend || true
            docker rm backend || true

            docker run -d \
            --name backend \
            -p 3001:3001 \
            --restart unless-stopped \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e PORT=3001 \
            -e NODE_ENV=production \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e MAIL_HOST="${{ secrets.MAIL_HOST }}" \
            -e MAIL_PORT="${{ secrets.MAIL_PORT }}" \
            -e MAIL_USER="${{ secrets.MAIL_USER }}" \
            -e MAIL_PASS="${{ secrets.MAIL_PASS }}" \
            -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
            -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            -e GOOGLE_CALLBACK_URL="${{ secrets.GOOGLE_CALLBACK_URL }}" \
            ${{ secrets.DOCKER_USERNAME }}/taskcraft-backend:latest
